In [20]:
from PIL import Image
import numpy as np
from skimage.measure import label, regionprops, regionprops_table

In [21]:
# Get test data
fpath = 'bw_new.tif'

# Open the tiff image
pil_img = Image.open(fpath)

# Map PIL mode to numpy dtype (note this may need to be extended)
dtype = {'F': np.float32, '1': np.uint8}[pil_img.mode]

# Load the data into a flat numpy array and reshape
np_img = np.array(pil_img.getdata(), dtype=dtype)
w, h = pil_img.size
np_img.shape = (h, w, np_img.size // (w * h))

In [22]:
# Verify dims match with Matlab image
assert np_img.shape[:2] == (8120, 4458)

In [23]:
# Label the connected components
label_img = label(np_img)


In [24]:
# Get connected components properties
regions = regionprops(label_img)

In [25]:
# Get the areas
skimages_areas = np.array([p.area for p in regions])

# display first 10 values
skimages_areas[:10]

array([  76034,    4143,     284, 3619602,      33,      90,   21297,
         91426,       2,      33])

In [26]:
# Import areas from matlab's region props for same image
matlab_areas = np.genfromtxt('matlab_areas.csv', delimiter=',', dtype= int)

# first 10 values
matlab_areas[:10]

array([  76034,    4143,     284, 3619602,      33,      90,   21297,
         91426,       2,      33])

In [27]:
julia_imagecomp_areas =  np.genfromtxt('jl_imagecomp_areas.csv', delimiter=',', dtype= int)

# first 10 values
julia_imagecomp_areas[:10]

array([  76140,    4149,     288, 3620293,      34,      91,   21405,
         91750,       2,      33])

In [28]:
# Correlation matlab vs skimages
np.corrcoef(skimages_areas, matlab_areas)[0,1]

1.0

In [29]:
# Correlation matlab vs jl_imagecomp
np.corrcoef(skimages_areas, julia_imagecomp_areas)[0,1]

0.9999999773734712